### ISSUE TITLE
Demo video text is illegible

### ISSUE THREAD

**Issue by Slackadays** [tdeerenberg/Musort#3]
Even on my giant 4K monitor, it's hard to read any of the text in the demo video. Additionally, the video controls take up some valuable space.

 I propose that you record a new video where the text is **huuge** and that it be in GIF form on GH. The trick to making a GIF is to use ffmpeg to convert it from regular form to a GIF with the right color palette.

If you want, I could send in a PR for a new demo GIF because they're a little tricky to make.

**Comment by tdeerenberg** [comment]
That is odd, I am able to read the text on all my devices (including 4k devices). Anyways, feel free to create a PR with a demo GIF if you feel the need for it :).
